config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [:index]
  resources :bio, only: [:index]
  resources :live_clients, :path => 'live', only: [:index]

  resources :studio_clients, :path => 'studio', only: [:index] do
    resources :tracks, only: [:index]
  end

  namespace :admin do
    root to: 'home#index', layout: 'admin'
    resources :bio, only: [:index], layout: 'admin'
    resources :live_clients, :path => 'live'
    resources :studio_clients, :path => 'studio' do
      resources :tracks
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
  # resources :users
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
end

app/models/live_client.rb
class LiveClient < ActiveRecord::Base
  validates :artist, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/admin/live_clients_controller.rb
class Admin::LiveClientsController < AdminController
  before_action :set_live_client, only: [:show, :edit, :update, :destroy]

  # GET /live_clients
  # GET /live_clients.json
  def index
    @live_clients = LiveClient.all
  end

  # GET /live_clients/1
  # GET /live_clients/1.json
  def show
  end

  # GET /live_clients/new
  def new
    @live_client = LiveClient.new
  end

  # GET /live_clients/1/edit
  def edit
  end

  # POST /live_clients
  # POST /live_clients.json
  def create
    @live_client = LiveClient.new(live_client_params)

    respond_to do |format|
      if @live_client.save
        format.html { redirect_to admin_live_clients_path, notice: 'Saved.' }
        format.json { render :show, status: :created, location: @live_client }
      else
        format.html { render :new }
        format.json { render json: @live_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_clients/1
  # PATCH/PUT /live_clients/1.json
  def update
    respond_to do |format|
      if @live_client.update(live_client_params)
        format.html { redirect_to edit_admin_live_client_path(@live_client), notice: 'Saved.' }
        format.json { render :show, status: :ok, location: @live_client }
      else
        format.html { render :edit }
        format.json { render json: @live_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_clients/1
  # DELETE /live_clients/1.json
  def destroy
    @live_client.destroy
    respond_to do |format|
      format.html { redirect_to admin_live_clients_path, notice: 'Deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_client
      @live_client = LiveClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def live_client_params
      params.require(:live_client).permit(:artist, :image, :remote_image_url, :contact, :soundcloud)
    end
end

app/controllers/live_clients_controller.rb
class LiveClientsController < ApplicationController
  before_action :set_live_client, only: [:show, :edit, :update, :destroy]

  # GET /live_clients
  # GET /live_clients.json
  def index
    @live_clients = LiveClient.all
  end

  # GET /live_clients/1
  # GET /live_clients/1.json
  def show
  end

  # GET /live_clients/new
  def new
    @live_client = LiveClient.new
  end

  # GET /live_clients/1/edit
  def edit
  end

  # POST /live_clients
  # POST /live_clients.json
  def create
    @live_client = LiveClient.new(live_client_params)

    respond_to do |format|
      if @live_client.save
        format.html { redirect_to @live_client, notice: 'Live Client Created' }
        format.json { render :show, status: :created, location: @live_client }
      else
        format.html { render :new }
        format.json { render json: @live_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_clients/1
  # PATCH/PUT /live_clients/1.json
  def update
    respond_to do |format|
      if @live_client.update(live_client_params)
        format.html { redirect_to @live_client, notice: 'Saved' }
        format.json { render :show, status: :ok, location: @live_client }
      else
        format.html { render :edit }
        format.json { render json: @live_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_clients/1
  # DELETE /live_clients/1.json
  def destroy
    @live_client.destroy
    respond_to do |format|
      format.html { redirect_to live_clients_url, notice: 'Live Client Deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live_client
      @live_client = LiveClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def live_client_params
      params.require(:live_client).permit(:artist, :image, :contact, :soundcloud)
    end
end

app/helpers/live_clients_helper.rb
module LiveClientsHelper
end

app/views/admin/live_clients/_form.html.erb
<%= form_for([:admin, @live_client], multipart: true) do |f| %>
  <% if @live_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@live_client.errors.count, "error") %> prohibited this live_client from being saved:</h2>

      <ul>
      <% @live_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field artist">
    <%= f.text_field :artist, placeholder: 'artist' %>
  </div>
  <div class="upload">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field image">
    <%= f.text_field :remote_image_url, placeholder: 'or paste an image link' %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/admin/live_clients/edit.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'live'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed live', page: 'live'} do %>
  <% end %>
<% end %>
<div class="list">
  <div class="live-client">
    <%= image_tag @live_client.image_url.to_s, class: 'artist-pic' %>
    <div class="info">
      <p class="artist"><%= @live_client.artist %></p>
      <% if @live_client.soundcloud and @live_client.soundcloud.length > 0 %>
        <%= image_tag 'play.png', class: 'play' %>
        <%= @live_client.soundcloud.html_safe %>
        <%= image_tag 'delete.png', class: 'sc-delete' %>
      <% end %>
    </div>
  </div>
  <div class="live-client">
    <img src="<%= @live_client.image %>" alt="" class="artist-pic"/>
    <p class="edit-label">
      Front
    </p>
  </div>
  <div class="live-client">
    <div class="info back">
      <p class="edit-label">
        Back
      </p>
      <p class="artist"><%= @live_client.artist %></p>
    </div>
  </div>
  <div class="live-client">
    <p class="edit-label">
      Edit
    </p>
    <%= render 'form' %>
    <%= link_to image_tag('delete.png'), admin_live_client_path(@live_client), method: :delete, data: { confirm: 'You want to delete this?' } %>
  </div>
</div>

app/views/admin/live_clients/index.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'live'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed live', page: 'live'} do %>
  <% end %>
<% end %>
<div class="list">
  <%= render 'shared/menu' %>
  <% @live_clients.reverse_each do |live_client| %>
    <div class="live-client">
      <%= image_tag live_client.image_url.to_s, class: 'artist-pic' %>
      <div class="info">
        <a href="<%= edit_admin_live_client_path(live_client) %>">
          <p class="artist"><%= live_client.artist %></p>
        </a>
      </div>
    </div>
  <% end %>
  <div class="live-client">
    <%= link_to image_tag('add.png'), new_admin_live_client_path, class:'add' %>
  </div>
</div>

app/views/admin/live_clients/new.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'live'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed live', page: 'live'} do %>
  <% end %>
<% end %>
<div class="list">
  <div class="live-client">
    <p class='new-label'>
      New Live Client
    </p>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/live_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @live_client.artist %>
</p>

<p>
  <strong>Image:</strong>
  <%= @live_client.image %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @live_client.contact %>
</p>

<%= link_to 'Edit', edit_admin_live_client_path(@live_client) %> |
<%= link_to 'Back', live_clients_path %>