config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [:index]
  resources :bio, only: [:index]
  resources :live_clients, :path => 'live', only: [:index]

  resources :studio_clients, :path => 'studio', only: [:index] do
    resources :tracks, only: [:index]
  end

  namespace :admin do
    root to: 'home#index', layout: 'admin'
    resources :bio, only: [:index], layout: 'admin'
    resources :live_clients, :path => 'live'
    resources :studio_clients, :path => 'studio' do
      resources :tracks
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
  # resources :users
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
end

app/models/live_client.rb
class LiveClient < ActiveRecord::Base
  validates :artist, presence: true
  mount_uploader :image, ImageUploader
end

app/models/studio_client.rb
class StudioClient < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  validates :artist, :album, :role, presence: true
  mount_uploader :image, ImageUploader
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :studio_client

  validates :title, presence: true
  validates :studio_client_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true
  has_secure_password
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_action :authorize

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

  def index
    render :'bio/index'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render :'home/index'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_name(params[:name])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_root_path
    else
      redirect_to login_path, notice: 'Name or Password incorrect'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    redirect_to studio_clients_path
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to studio_client_path(@track.studio_client_id), notice: 'Track was successfully added.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { redirect_to studio_clients_path, notice: "You need to include a title for the track" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to studio_client_path(@track.studio_client_id), notice: 'Live client was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { redirect_to studio_clients_path, notice: 'Didnt save edit for some reason' }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to studio_client_path(@track.studio_client_id), notice: 'Track deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :studio_client_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/live_clients_helper.rb
module LiveClientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/studio_clients_helper.rb
module StudioClientsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noah Giffin | Audio Engineer</title>
  <link rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css" media="screen" title="no title" charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://w.soundcloud.com/player/api.js" type="text/javascript"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <a href="<%= admin_root_path %>">
        <span class="noah">Noah Giffin</span>
      </a>
      <div class="audio-engineer"><div class="overline"></div><%= link_to "Logout", '/logout' %></div>
    </div>
    <div class="content">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="copyright">
        <span>&copy;2016 Noah Giffin Sound</span>
      </div>
      <div class="social-medias">
        <div class="social-media"><a href="https://www.instagram.com/noahgiffin" target='_blank'><img src="<%= asset_path "instagram.png" %>" /></a></div>
        <div class="social-media"><a href="https://www.facebook.com/noah.giffin" target='_blank'><img src="<%= asset_path "facebook.png" %>" /></a></div>
        <div class="social-media"><a href="mailto:noah.giffin@gmail.com"><img src="<%= asset_path "mail.png" %>" /></a></div>
      </div>
      <div class="copyright dorian">
        <span>web designed by Dorian Thornton</span>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noah Giffin | Audio Engineer</title>
  <link rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css" media="screen" title="no title" charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://w.soundcloud.com/player/api.js" type="text/javascript"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <% if current_user %>
        <a href="<%= admin_root_path %>">
      <% else %>
        <a href="<%= root_path %>">
      <% end %>
        <span class="noah">Noah Giffin</span>
      </a>
        <div class="audio-engineer"><div class="overline"></div></div>
    </div>
    <div class="content">
      <%= yield %>
    </div>
    <div class="footer">
      <% if current_user %>
        <div class="logout">
          <%= link_to "Logout", '/logout' %>
        </div>
      <% else %>
        <div class="copyright">
          <span><a href="<%= login_path%>" class='secret'>&copy;</a>2016 Noah Giffin Sound</span>
        </div>
        <div class="social-medias">
          <div class="social-media"><a href="https://www.instagram.com/noahgiffin" target='_blank'><img src="<%= asset_path "instagram.png" %>" /></a></div>
          <div class="social-media"><a href="https://www.facebook.com/noah.giffin" target='_blank'><img src="<%= asset_path "facebook.png" %>" /></a></div>
          <div class="social-media"><a href="mailto:noah.giffin@gmail.com"><img src="<%= asset_path "mail.png" %>" /></a></div>
        </div>
        <div class="copyright dorian">
          <span>web designed by Dorian Thornton</span>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/shared/_menu.html.erb
<% if current_user %>
  <a href="<%= admin_root_path %>">
<% else %>
  <a href="<%= root_path %>">
<% end %>
  <div class="menu-item home">
    <%= image_tag('eq98.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        home
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_bio_index_path %>">
<% else %>
  <a href="<%= bio_index_path %>">
<% end %>
  <div class="menu-item bio">
    <%= image_tag('eq85.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        bio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_studio_clients_path %>">
<% else %>
  <a href="<%= studio_clients_path %>">
<% end %>
  <div class="menu-item studio">
    <%= image_tag('eq59.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        studio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_live_clients_path %>">
<% else %>
  <a href='<%= live_clients_path %>'>
<% end %>
  <div class="menu-item live">
    <%= image_tag('eq91.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        live
      </p>
    </span>
  </div>
</a>

app/views/shared/_menu2.html.erb
<% if current_user %>
  <a href="<%= admin_root_path %>">
<% else %>
  <a href="<%= root_path %>">
<% end %>
  <div class="menu-item home">
    <%= image_tag('eq59.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        home
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_bio_index_path %>">
<% else %>
  <a href="<%= bio_index_path %>">
<% end %>
  <div class="menu-item bio">
    <%= image_tag('eq98.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        bio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_studio_clients_path %>">
<% else %>
  <a href="<%= studio_clients_path %>">
<% end %>
  <div class="menu-item studio">
    <%= image_tag('eq87.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        studio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_live_clients_path %>">
<% else %>
  <a href='<%= live_clients_path %>'>
<% end %>
  <div class="menu-item live">
    <%= image_tag('eq72.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        live
      </p>
    </span>
  </div>
</a>

app/views/shared/_menu3.html.erb
<% if current_user %>
  <a href="<%= admin_root_path %>">
<% else %>
  <a href="<%= root_path %>">
<% end %>
  <div class="menu-item home">
    <%= image_tag('eq108.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        home
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_bio_index_path %>">
<% else %>
  <a href="<%= bio_index_path %>">
<% end %>
  <div class="menu-item bio">
    <%= image_tag('eq87.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        bio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_studio_clients_path %>">
<% else %>
  <a href="<%= studio_clients_path %>">
<% end %>
  <div class="menu-item studio">
    <%= image_tag('eq76.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        studio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_live_clients_path %>">
<% else %>
  <a href='<%= live_clients_path %>'>
<% end %>
  <div class="menu-item live">
    <%= image_tag('eq63.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        live
      </p>
    </span>
  </div>
</a>

app/views/shared/_menu4.html.erb
<% if current_user %>
  <a href="<%= admin_root_path %>">
<% else %>
  <a href="<%= root_path %>">
<% end %>
  <div class="menu-item home">
    <%= image_tag('eq76.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        home
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_bio_index_path %>">
<% else %>
  <a href="<%= bio_index_path %>">
<% end %>
  <div class="menu-item bio">
    <%= image_tag('eq63.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class="info">
      <p>
        bio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_studio_clients_path %>">
<% else %>
  <a href="<%= studio_clients_path %>">
<% end %>
  <div class="menu-item studio">
    <%= image_tag('eq34.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        studio
      </p>
    </span>
  </div>
</a>
<% if current_user %>
  <a href="<%= admin_live_clients_path %>">
<% else %>
  <a href='<%= live_clients_path %>'>
<% end %>
  <div class="menu-item live">
    <%= image_tag('eq44.png', class: 'jpg') %>
    <%= image_tag('equalizer.gif', class: 'gif') %>
    <span class='info'>
      <p>
        live
      </p>
    </span>
  </div>
</a>

app/views/shared/_sc_widget.html.erb
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/210918650&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>