config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [:index]
  resources :bio, only: [:index]
  resources :live_clients, :path => 'live', only: [:index]

  resources :studio_clients, :path => 'studio', only: [:index] do
    resources :tracks, only: [:index]
  end

  namespace :admin do
    root to: 'home#index', layout: 'admin'
    resources :bio, only: [:index], layout: 'admin'
    resources :live_clients, :path => 'live'
    resources :studio_clients, :path => 'studio' do
      resources :tracks
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
  # resources :users
  # get '/signup' => 'users#new'
  # post '/users' => 'users#create'
  # DELETE THIS SHIT ONCE NOAH IS SIGNED UP
end

app/models/studio_client.rb
class StudioClient < ActiveRecord::Base
  has_many :tracks, dependent: :destroy
  validates :artist, :album, :role, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/admin/studio_clients_controller.rb
class Admin::StudioClientsController < AdminController
  before_action :set_studio_client, only: [:show, :edit, :update, :destroy]

  # GET /studio_clients
  # GET /studio_clients.json
  def index
    @studio_clients = StudioClient.all
    @tracks = Track.all
  end

  # GET /studio_clients/1
  # GET /studio_clients/1.json
  def show
    @track = Track.new
  end

  # GET /studio_clients/new
  def new
    @studio_client = StudioClient.new
  end

  # GET /studio_clients/1/edit
  def edit
    @track = Track.new
  end

  # POST /studio_clients
  # POST /studio_clients.json
  def create
    @studio_client = StudioClient.new(studio_client_params)

    respond_to do |format|
      if @studio_client.save
        format.html { redirect_to edit_admin_studio_client_path(@studio_client), notice: 'Saved.' }
        format.json { render :show, status: :created, location: @studio_client }
      else
        format.html { render :new }
        format.json { render json: @studio_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studio_clients/1
  # PATCH/PUT /studio_clients/1.json
  def update

    respond_to do |format|
      if @studio_client.update(studio_client_params)
        format.html { redirect_to edit_admin_studio_client_path(@studio_client), notice: 'Saved.' }
        format.json { render :show, status: :ok, location: @studio_client }
      else
        Rails.logger.info(@studio_client.errors.inspect)
        format.html { render :edit }
        format.json { render json: @studio_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studio_clients/1
  # DELETE /studio_clients/1.json
  def destroy
    @studio_client.destroy
    respond_to do |format|
      format.html { redirect_to studio_clients_url, notice: 'Deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio_client
      @studio_client = StudioClient.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studio_client_params
      params.require(:studio_client).permit(:artist, :image, :remote_image_url, :album, :role, :soundcloud)
    end
end

app/controllers/studio_clients_controller.rb
class StudioClientsController < ApplicationController
  before_action :set_studio_client, only: [:show, :edit, :update, :destroy]

  # GET /studio_clients
  # GET /studio_clients.json
  def index
    @studio_clients = StudioClient.all
    @tracks = Track.all
  end

  # GET /studio_clients/1
  # GET /studio_clients/1.json
  def show
    @track = Track.new
  end

  # GET /studio_clients/new
  def new
    @studio_client = StudioClient.new
  end

  # GET /studio_clients/1/edit
  def edit
  end

  # POST /studio_clients
  # POST /studio_clients.json
  def create
    @studio_client = StudioClient.new(studio_client_params)

    respond_to do |format|
      if @studio_client.save
        format.html { redirect_to @studio_client, notice: 'Studio client was successfully created.' }
        format.json { render :show, status: :created, location: @studio_client }
      else
        format.html { render :new }
        format.json { render json: @studio_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studio_clients/1
  # PATCH/PUT /studio_clients/1.json
  def update
    respond_to do |format|
      if @studio_client.update(studio_client_params)
        format.html { redirect_to admin_studio_client_path(@studio_client), notice: 'Studio client was successfully updated.' }
        format.json { render :show, status: :ok, location: @studio_client }
      else
        format.html { render :edit }
        format.json { render json: @studio_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studio_clients/1
  # DELETE /studio_clients/1.json
  def destroy
    @studio_client.destroy
    respond_to do |format|
      format.html { redirect_to studio_clients_url, notice: 'Studio client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studio_client
      @studio_client = StudioClient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studio_client_params
      params.require(:studio_client).permit(:artist, :image, :album, :role, :soundcloud)
    end
end

app/helpers/studio_clients_helper.rb
module StudioClientsHelper
end

app/views/admin/studio_clients/_form.html.erb
<%= form_for([:admin, @studio_client], multipart: true) do |f| %>
  <% if @studio_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@studio_client.errors.count, "error") %> prohibited this studio_client from being saved:</h2>

      <ul>
      <% @studio_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="studio-field artist">
    <%= f.text_field :artist, placeholder: 'artist' %>
  </div>
  <div class="studio-field album">
    <%= f.text_field :album, placeholder: 'album or track' %>
  </div>
  <div class="studio-field role">
    <%= f.text_field :role, placeholder: 'role' %>
  </div>
  <div class="upload">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="studio-field image">
    <%= f.text_field :remote_image_url, placeholder: 'or paste an image link' %>
  </div>
  <div class="studio-field soundcloud">
    <%= f.label 'soundcloud link' %>
    <%= f.text_field :soundcloud, placeholder: 'soundcloud link' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/admin/studio_clients/_track_form.html.erb
<%= form_for([:admin, @studio_client, @track]) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <%= f.hidden_field :studio_client_id, value: @studio_client.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/studio_clients/edit.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'studio'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed in the studio', page: 'studio'} do %>
  <% end %>
<% end %>
<div class="list">
  <div class="studio-client">
    <%= image_tag @studio_client.image_url.to_s, class: 'artist-pic' %>
    <span class="info">
      <div class="artist"><%= @studio_client.artist %></div>
      <div class="album"><%= @studio_client.album %></div>
      <div class="role"><%= @studio_client.role %></div>
      <% if @studio_client.soundcloud and @studio_client.soundcloud.length > 0 %>
        <%= image_tag 'play.png', class: 'play' %>
        <%= @studio_client.soundcloud.html_safe %>
        <%= image_tag 'delete.png', class: 'sc-delete' %>
      <% end %>
    </span>
  </div>
  <div class="studio-client">
    <p class="edit-label">
      Front
    </p>
    <img src="<%= @studio_client.image %>" alt="" class="artist-pic"/>
  </div>
  <div class="studio-client">
    <div class="info back">
      <p class="edit-label">
        Back
      </p>
      <div class='artist'>
        <%= @studio_client.artist %>
      </div>

      <div class='album'>
        <%= @studio_client.album %>
      </div>

      <div class='role'>
        <%= @studio_client.role %>
      </div>
      <% if @studio_client.soundcloud and @studio_client.soundcloud.length > 0 %>
        <%= image_tag 'play.png', class: 'play' %>
        <%= @studio_client.soundcloud.html_safe %>
        <%= image_tag 'delete.png', class: 'sc-delete' %>
      <% end %>
    </div>
  </div>
  <div class="studio-client">
    <p class="edit-label">
      Edit
    </p>
    <%= render 'form' %>
    <%= link_to image_tag('delete.png'), admin_studio_client_path(@studio_client), method: :delete, data: { confirm: 'You want to delete this?' } %>
  </div>
</div>

app/views/admin/studio_clients/index.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'studio'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed in the studio', page: 'studio'} do %>
  <% end %>
<% end %>
<div class="list">
  <%= render 'shared/menu' %>
  <% @studio_clients.reverse_each do |studio_client| %>
    <div class="studio-client">
      <%= image_tag studio_client.image_url.to_s, class: 'artist-pic' %>
      <span class="info">
        <a href="<%= edit_admin_studio_client_path(studio_client) %>">
          <div class="artist"><%= studio_client.artist %></div>
        </a>
        <div class="album"><%= studio_client.album %></div>
        <div class="role"><%= studio_client.role %></div>
        <% if studio_client.soundcloud and studio_client.soundcloud.length > 0 %>
          <%= image_tag 'play.png', class: 'play' %>
          <%= studio_client.soundcloud.html_safe %>
          <%= image_tag 'delete.png', class: 'sc-delete' %>
        <% end %>
      </span>
    </div>
  <% end %>

  <div class="studio-client">
    <%= link_to image_tag('add.png'), new_admin_studio_client_path, class:'add' %>
  </div>

</div>

app/views/admin/studio_clients/new.html.erb
<% if notice %>
  <%= content_tag "div", class:'header-info', data: {text: notice, page: 'studio'} do %>
  <% end %>
<% else %>
  <%= content_tag "div", class:'header-info', data: {text: 'bands mixed in the studio', page: 'studio'} do %>
  <% end %>
<% end %>
<div class="list">
    <div class="studio-client">
      <p class='new-label'>
        New Studio Client
      </p>
      <%= render 'form' %>
    </div>
</div>

app/views/admin/studio_clients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="studio-client">
  <div class='artist'>
    <%= @studio_client.artist %>
  </div>

  <div class='image'>
    <img src="<%= @studio_client.image %>" alt="" />
  </div>

  <div class='album'>
    <%= @studio_client.album %>
  </div>

  <div class='role'>
    <%= @studio_client.role %>
  </div>

  <% @studio_client.tracks.each do |track| %>
    <div class="track">
      <p> <%= track.title %></p>
      <%= link_to image_tag('delete.png'), studio_client_track_path(@studio_client, track), method: :delete %>
    </div>

  <% end %>
</div>
<div class="studio-client">
  <p>
    Edit
  </p>
  <%= render 'form' %>
  <%= render 'track_form' %>
</div>